# Generated by Django 5.1 on 2024-09-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted DateTime')),
                ('name', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('display_fullname', models.CharField(blank=True, max_length=256, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('next_build_number', models.IntegerField(blank=True, null=True)),
                ('first_build_number', models.IntegerField(blank=True, null=True)),
                ('last_build_number', models.IntegerField(blank=True, null=True)),
                ('last_stable_build_number', models.IntegerField(blank=True, null=True)),
                ('last_unstable_build_number', models.IntegerField(blank=True, null=True)),
                ('last_completed_build_number', models.IntegerField(blank=True, null=True)),
                ('last_failed_build_number', models.IntegerField(blank=True, null=True)),
                ('last_successful_build_number', models.IntegerField(blank=True, null=True)),
                ('last_unsuccessful_build_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'JobModel',
                'verbose_name_plural': 'JobModel',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='PipelineBuildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted DateTime')),
                ('number', models.IntegerField()),
                ('submitter', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('display_name', models.CharField(max_length=128)),
                ('display_fullname', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('duration_estimated_seconds', models.IntegerField()),
                ('result', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'PipelineBuildModel',
                'verbose_name_plural': 'PipelineBuildModel',
                'db_table': 'pipeline_build',
            },
        ),
        migrations.CreateModel(
            name='PipelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted DateTime')),
                ('name', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('description', models.TextField(max_length=1024)),
                ('display_name', models.CharField(max_length=128)),
                ('display_fullname', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=32)),
                ('next_build_number', models.IntegerField()),
                ('first_build_number', models.IntegerField()),
                ('last_build_number', models.IntegerField()),
                ('last_completed_build_number', models.IntegerField()),
                ('last_failed_build_number', models.IntegerField()),
                ('last_successful_build_number', models.IntegerField()),
                ('last_unsuccessful_build_number', models.IntegerField()),
                ('last_stable_build_number', models.IntegerField()),
                ('last_unstable_build_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'PipelineModel',
                'verbose_name_plural': 'PipelineModel',
                'db_table': 'pipeline',
            },
        ),
        migrations.CreateModel(
            name='PipelineBuildStageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted DateTime')),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=16)),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('pipeline_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dj_jenkins.pipelinebuildmodel')),
            ],
            options={
                'verbose_name': 'PipelineBuildStageModel',
                'verbose_name_plural': 'PipelineBuildStageModel',
                'db_table': 'pipeline_build_stage',
            },
        ),
        migrations.AddField(
            model_name='pipelinebuildmodel',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dj_jenkins.pipelinemodel'),
        ),
        migrations.CreateModel(
            name='JobBuildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted DateTime')),
                ('number', models.IntegerField()),
                ('submitter', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_estimated', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=16, null=True)),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('next_build_number', models.IntegerField(blank=True, null=True)),
                ('previous_build_number', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dj_jenkins.jobmodel')),
            ],
            options={
                'verbose_name': 'JobBuildModel',
                'verbose_name_plural': 'JobBuildModel',
                'db_table': 'job_build',
                'unique_together': {('job', 'number')},
            },
        ),
    ]
